const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

// =====================================================================
// COMPLETE DEDUPLICATED PRODUCT CATALOG
// All images: official brand/retailer pages. No Unsplash.
// Prices in INR. Official URLs verified.
// =====================================================================
const CATALOG = [

  // ================================================================
  // PHOTOGRAPHY
  // ================================================================

  // -- CAMERAS --
  { hobby: 'Photography', category: 'Cameras', brand: 'Sony', product_name: 'Sony Alpha 7 IV', price: 214990, image_url: 'https://m.media-amazon.com/images/I/71XmPxtf1VL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/interchangeable-lens-cameras/ilce-7m4', source_type: 'official_product_page', description: '33MP full-frame mirrorless camera with advanced autofocus.' },
  { hobby: 'Photography', category: 'Cameras', brand: 'Canon', product_name: 'Canon EOS R6 Mark II', price: 243995, image_url: 'https://m.media-amazon.com/images/I/61mrLpwYEVL._SX679_.jpg', official_url: 'https://in.canon/en/consumer/eos-r6-mark-ii-body/product', source_type: 'official_product_page', description: '40fps full-frame mirrorless for photo and video.' },
  { hobby: 'Photography', category: 'Cameras', brand: 'Nikon', product_name: 'Nikon Z8', price: 343995, image_url: 'https://m.media-amazon.com/images/I/81M1zD4dDdL._SX679_.jpg', official_url: 'https://www.nikon.co.in/mirrorless-z-8', source_type: 'official_product_page', description: 'Flagship compact full-frame mirrorless, 45.7MP.' },
  { hobby: 'Photography', category: 'Cameras', brand: 'Fujifilm', product_name: 'Fujifilm X-T5', price: 169999, image_url: 'https://m.media-amazon.com/images/I/71R2H0N2kZL._SX679_.jpg', official_url: 'https://fujifilm-x.com/en-in/products/cameras/x-t5/', source_type: 'official_product_page', description: '40.2MP APS-C mirrorless with classic dial controls.' },
  { hobby: 'Photography', category: 'Cameras', brand: 'Sony', product_name: 'Sony ZV-E10 II', price: 79990, image_url: 'https://m.media-amazon.com/images/I/71Qjm5B2FdL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/interchangeable-lens-cameras/ilczve10m2', source_type: 'official_product_page', description: 'Creator-focused APS-C mirrorless for vlogging.' },

  // -- LENSES --
  { hobby: 'Photography', category: 'Lenses', brand: 'Sigma', product_name: 'Sigma 35mm f/1.4 DG HSM Art', price: 74000, image_url: 'https://m.media-amazon.com/images/I/61kM2G-0m9L._SX679_.jpg', official_url: 'https://www.sigma-global.com/en/lenses/a_35_14/', source_type: 'official_product_page', description: 'Reference-class prime with stunning rendering.' },
  { hobby: 'Photography', category: 'Lenses', brand: 'Tamron', product_name: 'Tamron 28-75mm f/2.8 Di III VXD G2', price: 75000, image_url: 'https://m.media-amazon.com/images/I/61Z+-tE9VGL._SX679_.jpg', official_url: 'https://www.tamron.in/product/a063', source_type: 'official_product_page', description: 'Fast standard zoom for Sony E-mount shooters.' },
  { hobby: 'Photography', category: 'Lenses', brand: 'Sony', product_name: 'Sony FE 50mm f/1.2 GM', price: 169990, image_url: 'https://m.media-amazon.com/images/I/71u9s9WnLNL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/camera-lenses/sel50f12gm', source_type: 'official_product_page', description: 'G Master 50mm with unmatched resolution and bokeh.' },
  { hobby: 'Photography', category: 'Lenses', brand: 'Sigma', product_name: 'Sigma 100-400mm f/5-6.3 DG DN OS', price: 78999, image_url: 'https://m.media-amazon.com/images/I/71A2g7rNLcL._SX679_.jpg', official_url: 'https://www.sigma-global.com/en/lenses/c_100400_56_63/', source_type: 'official_product_page', description: 'Wildlife telephoto zoom for Sony/L-mount.' },
  { hobby: 'Photography', category: 'Lenses', brand: 'Samyang', product_name: 'Samyang 12mm f/2.0 AF', price: 29999, image_url: 'https://m.media-amazon.com/images/I/51a5yuOZ7bL._SX679_.jpg', official_url: 'https://www.samyanglens.com/en/product/product-view.php?seq=493', source_type: 'official_product_page', description: 'Ultra-wide autofocus lens for APS-C mirrorless.' },

  // -- TRIPODS --
  { hobby: 'Photography', category: 'Tripods', brand: 'Manfrotto', product_name: 'Manfrotto MT055CXPRO4', price: 34999, image_url: 'https://m.media-amazon.com/images/I/41yZNOvJ5iL._SX679_.jpg', official_url: 'https://www.manfrotto.com/in-en/055-carbon-fiber-4-section-tripod-with-horizontal-column-mt055cxpro4/', source_type: 'official_product_page', description: 'Carbon fiber 4-section pro tripod with 90° column.' },
  { hobby: 'Photography', category: 'Tripods', brand: 'Sirui', product_name: 'Sirui T-2204XL Carbon Tripod', price: 22999, image_url: 'https://m.media-amazon.com/images/I/71Bsga7H0OL._SX679_.jpg', official_url: 'https://www.sirui.com/products/t-2204xl', source_type: 'official_product_page', description: 'Lightweight carbon fiber travel tripod.' },
  { hobby: 'Photography', category: 'Tripods', brand: 'Benro', product_name: 'Benro Mach3 TMA38CL', price: 19999, image_url: 'https://m.media-amazon.com/images/I/51IkuCMMGkL._SX679_.jpg', official_url: 'https://www.benro.com/en/product/product_info/id/3193.html', source_type: 'official_product_page', description: 'Mach3 series carbon fiber tripod, holds up to 18kg.' },

  // -- LIGHTING --
  { hobby: 'Photography', category: 'Lighting', brand: 'Godox', product_name: 'Godox AD200Pro Pocket Flash', price: 22500, image_url: 'https://m.media-amazon.com/images/I/71JpkpZKyxL._SX679_.jpg', official_url: 'https://www.godox.com/product/AD200Pro.html', source_type: 'official_product_page', description: '200Ws portable TTL flash with HSS.' },
  { hobby: 'Photography', category: 'Lighting', brand: 'Godox', product_name: 'Godox SL-60W LED Video Light', price: 9999, image_url: 'https://m.media-amazon.com/images/I/61E3M1GBGJL._SX679_.jpg', official_url: 'https://www.godox.com/product/SL60W.html', source_type: 'official_product_page', description: 'Bowens-mount 60W daylight LED studio light.' },
  { hobby: 'Photography', category: 'Lighting', brand: 'Aputure', product_name: 'Aputure LS 300X Bi-Color LED', price: 89999, image_url: 'https://m.media-amazon.com/images/I/61J8v7g8BTL._SX679_.jpg', official_url: 'https://www.aputure.com/products/ls-300x/', source_type: 'official_product_page', description: 'Pro bi-color LED light with CRI 96+.' },
  { hobby: 'Photography', category: 'Lighting', brand: 'Nanlite', product_name: 'Nanlite Forza 60B II Bi-Color LED', price: 27999, image_url: 'https://m.media-amazon.com/images/I/61yGNDyGr1L._SX679_.jpg', official_url: 'https://www.nanlite.com/products/forza-60b-ii', source_type: 'official_product_page', description: 'Compact 60W bi-color monolight for studio/location.' },
  { hobby: 'Photography', category: 'Lighting', brand: 'Neewer', product_name: 'Neewer NL660S RGB LED Panel', price: 7999, image_url: 'https://m.media-amazon.com/images/I/71OV4WlIZhL._SX679_.jpg', official_url: 'https://neewer.com/products/neewer-nl660s-led-video-light', source_type: 'official_product_page', description: 'Full RGB LED panel with CRI 97+ for video creators.' },

  // -- CAMERA BAGS --
  { hobby: 'Photography', category: 'Camera Bags', brand: 'Lowepro', product_name: 'Lowepro ProTactic BP 450 AW II', price: 22999, image_url: 'https://m.media-amazon.com/images/I/71qKDe09MmL._SX679_.jpg', official_url: 'https://www.lowepro.com/global-en/protactic-bp-450-aw-ii-lp37177/', source_type: 'official_product_page', description: 'Pro modular camera backpack for mirrorless/DSLR kits.' },
  { hobby: 'Photography', category: 'Camera Bags', brand: 'Peak Design', product_name: 'Peak Design Travel Backpack 45L', price: 34999, image_url: 'https://m.media-amazon.com/images/I/71TRH11u5RL._SX679_.jpg', official_url: 'https://www.peakdesign.com/products/travel-backpack', source_type: 'official_product_page', description: 'The gold-standard travel backpack for photographers.' },
  { hobby: 'Photography', category: 'Camera Bags', brand: 'Vanguard', product_name: 'Vanguard Alta Sky 51D', price: 12999, image_url: 'https://m.media-amazon.com/images/I/81c0Nk0EagL._SX679_.jpg', official_url: 'https://www.vanguardworld.com/bags_packs_us/alta-sky-51d.html', source_type: 'official_product_page', description: 'Dual access camera backpack with 18kg load capacity.' },

  // -- FILTERS --
  { hobby: 'Photography', category: 'Filters', brand: 'K&F Concept', product_name: 'K&F Concept 10-Stop ND1000 Filter 77mm', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71Ry3Sl34SL._SX679_.jpg', official_url: 'https://www.kentfaith.com/products/77mm-nd1000-filter', source_type: 'official_product_page', description: 'High definition 10-stop ND filter for long exposures.' },
  { hobby: 'Photography', category: 'Filters', brand: 'NiSi', product_name: 'NiSi S6 150mm Filter Holder Kit', price: 21999, image_url: 'https://m.media-amazon.com/images/I/71d5zYvYNAL._SX679_.jpg', official_url: 'https://nisifilters.com/products/nisi-s6-150mm-filter-holder-kit/', source_type: 'official_product_page', description: 'Professional 150mm filter system for ultra-wide lenses.' },
  { hobby: 'Photography', category: 'Filters', brand: 'Hoya', product_name: 'Hoya HD CPL 77mm Circular Polarizer', price: 6499, image_url: 'https://m.media-amazon.com/images/I/61CeDPXGRxL._SX679_.jpg', official_url: 'https://www.hoyafilter.com/product/hoya-hd-cpl/', source_type: 'official_product_page', description: 'Ultra-hard glass CPL filter with 8-layer coating.' },

  // -- DRONES --
  { hobby: 'Photography', category: 'Drones', brand: 'DJI', product_name: 'DJI Mini 4 Pro', price: 89000, image_url: 'https://m.media-amazon.com/images/I/61vY+P8YJQL._SX679_.jpg', official_url: 'https://www.dji.com/mini-4-pro', source_type: 'official_product_page', description: '4K/60fps drone under 249g with omnidirectional sensing.' },
  { hobby: 'Photography', category: 'Drones', brand: 'DJI', product_name: 'DJI Mavic 3 Pro', price: 219000, image_url: 'https://m.media-amazon.com/images/I/61dF-oNfB2L._SX679_.jpg', official_url: 'https://www.dji.com/mavic-3-pro', source_type: 'official_product_page', description: 'Flagship triple-camera Hasselblad imaging drone.' },
  { hobby: 'Photography', category: 'Drones', brand: 'DJI', product_name: 'DJI Air 3S', price: 109000, image_url: 'https://m.media-amazon.com/images/I/51Og+0XjM3L._SX679_.jpg', official_url: 'https://www.dji.com/air-3s', source_type: 'official_product_page', description: 'Versatile 1-inch CMOS drone with 46-min flight time.' },

  // -- GIMBALS & STABILIZERS --
  { hobby: 'Photography', category: 'Gimbals & Stabilizers', brand: 'DJI', product_name: 'DJI RS 3 Pro Gimbal', price: 42999, image_url: 'https://m.media-amazon.com/images/I/614hUlOfW-L._SX679_.jpg', official_url: 'https://www.dji.com/rs-3-pro', source_type: 'official_product_page', description: '3-axis camera stabilizer for DSLRs up to 4.5kg.' },
  { hobby: 'Photography', category: 'Gimbals & Stabilizers', brand: 'Zhiyun', product_name: 'Zhiyun Crane-M3S', price: 22999, image_url: 'https://m.media-amazon.com/images/I/71r5eLiwnUL._SX679_.jpg', official_url: 'https://store.zhiyun-tech.com/products/crane-m3s', source_type: 'official_product_page', description: 'Lightweight 3-axis gimbal for mirrorless cameras.' },
  { hobby: 'Photography', category: 'Gimbals & Stabilizers', brand: 'FeiyuTech', product_name: 'FeiyuTech AK2000C', price: 17999, image_url: 'https://m.media-amazon.com/images/I/71lnDKaTBRL._SX679_.jpg', official_url: 'https://www.feiyu-tech.com/product/ak2000c', source_type: 'official_product_page', description: 'Carbon fiber gimbal supporting 2.2kg cameras.' },

  // -- MEMORY CARDS & STORAGE --
  { hobby: 'Photography', category: 'Memory Cards & Storage', brand: 'SanDisk', product_name: 'SanDisk Extreme PRO 256GB SDXC V30', price: 3499, image_url: 'https://m.media-amazon.com/images/I/81a6HKBUNLL._SX679_.jpg', official_url: 'https://www.westerndigital.com/en-in/products/memory-cards/sandisk-extreme-pro-uhs-i-sd', source_type: 'official_product_page', description: '200MB/s read speed SD card for 4K video.' },
  { hobby: 'Photography', category: 'Memory Cards & Storage', brand: 'Samsung', product_name: 'Samsung PRO Plus 256GB microSDXC', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71Z2CpKO96L._SX679_.jpg', official_url: 'https://www.samsung.com/in/memory-storage/memory-card/pro-plus-microsdxc-256gb-mb-md256sa-am/', source_type: 'official_product_page', description: 'Pro-grade microSD with 180MB/s read.' },
  { hobby: 'Photography', category: 'Memory Cards & Storage', brand: 'Lexar', product_name: 'Lexar Professional 2000x 64GB CFexpress B', price: 9999, image_url: 'https://m.media-amazon.com/images/I/71k5PSDKQKL._SX679_.jpg', official_url: 'https://www.lexar.com/products/lexar-professional-2000x-cfexpress-type-b-card/', source_type: 'official_product_page', description: 'High-speed CFexpress for 8K/RAW burst shooting.' },

  // ================================================================
  // MUSIC
  // ================================================================

  // -- IEMs --
  { hobby: 'Music', category: 'IEMs', brand: 'Moondrop', product_name: 'Moondrop Aria Snow Edition', price: 6999, image_url: 'https://m.media-amazon.com/images/I/51pD-h+mZXL._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/moondrop-aria-snow-edition', source_type: 'distributor', description: '10mm LCP dynamic driver IEM, reference tuning.' },
  { hobby: 'Music', category: 'IEMs', brand: '7Hz', product_name: '7Hz Timeless', price: 18990, image_url: 'https://m.media-amazon.com/images/I/61R1w9b-7TL._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/7hz-timeless', source_type: 'distributor', description: 'Planar magnetic IEM with ultra-thin 14.2mm driver.' },
  { hobby: 'Music', category: 'IEMs', brand: 'Simgot', product_name: 'Simgot EM6L', price: 7999, image_url: 'https://m.media-amazon.com/images/I/61yUGHmUqXL._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/simgot-em6l', source_type: 'distributor', description: '1DD+4BA hybrid IEM with smooth natural timbre.' },
  { hobby: 'Music', category: 'IEMs', brand: 'Truthear', product_name: 'Truthear x Crinacle ZERO:RED', price: 5999, image_url: 'https://m.media-amazon.com/images/I/51J7pZh-v4L._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/truthear-x-crinacle-zero-red', source_type: 'distributor', description: 'Dual dynamic driver IEM with warm V-shaped signature.' },
  { hobby: 'Music', category: 'IEMs', brand: 'KZ', product_name: 'KZ ZSN Pro X', price: 1499, image_url: 'https://m.media-amazon.com/images/I/613MqzNYBYL._SX679_.jpg', official_url: 'https://www.amazon.in/KZ-ZSN-Pro-X/dp/B08F9RZMFZ', source_type: 'distributor', description: 'Budget 1DD+1BA hybrid IEM, entry-level audiophile pick.' },
  { hobby: 'Music', category: 'IEMs', brand: 'Fiio', product_name: 'Fiio FH5S', price: 17999, image_url: 'https://m.media-amazon.com/images/I/61XU5rjdCBL._SX679_.jpg', official_url: 'https://www.fiio.com/fh5s', source_type: 'official_product_page', description: '1DD+3BA IEM with detachable MMCX cable.' },

  // -- DACs & AMPS --
  { hobby: 'Music', category: 'DACs & Amps', brand: 'Fiio', product_name: 'Fiio K7 Desktop DAC/Amp', price: 18999, image_url: 'https://m.media-amazon.com/images/I/71wjrBmFO3L._SX679_.jpg', official_url: 'https://www.fiio.com/k7', source_type: 'official_product_page', description: 'Balanced desktop DAC/Amp with AK4493SEQ.' },
  { hobby: 'Music', category: 'DACs & Amps', brand: 'iFi Audio', product_name: 'iFi Hip-dac 3 Portable DAC/Amp', price: 12999, image_url: 'https://m.media-amazon.com/images/I/61zAJLd5nLL._SX679_.jpg', official_url: 'https://ifi-audio.com/products/hip-dac3/', source_type: 'official_product_page', description: 'Pocket-sized USB DAC/Amp for audiophiles on the go.' },
  { hobby: 'Music', category: 'DACs & Amps', brand: 'Topping', product_name: 'Topping DX3 Pro+ DAC/Amp', price: 13999, image_url: 'https://m.media-amazon.com/images/I/61TZJv2R7tL._SX679_.jpg', official_url: 'https://www.toppingaudio.com/product-item/dx3-pro/', source_type: 'official_product_page', description: 'All-in-one desktop DAC + headphone amplifier.' },
  { hobby: 'Music', category: 'DACs & Amps', brand: 'Shanling', product_name: 'Shanling UA2 Portable DAC', price: 7999, image_url: 'https://m.media-amazon.com/images/I/51j7eBJsGqL._SX679_.jpg', official_url: 'https://en.shanlingmusic.com/UA2', source_type: 'official_product_page', description: 'Compact USB-C dongle DAC/Amp with balanced out.' },
  { hobby: 'Music', category: 'DACs & Amps', brand: 'Moondrop', product_name: 'Moondrop Dawn Pro DAC/Amp', price: 4999, image_url: 'https://m.media-amazon.com/images/I/61LUvgQ1bNL._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/moondrop-dawn-pro', source_type: 'distributor', description: 'Budget dongle DAC/Amp with ES9219C chip.' },

  // -- HEADPHONES --
  { hobby: 'Music', category: 'Headphones', brand: 'Sony', product_name: 'Sony WH-1000XM5', price: 29990, image_url: 'https://m.media-amazon.com/images/I/51aXvjzcukL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/headband-headphones/wh-1000xm5', source_type: 'official_product_page', description: 'Industry-leading noise canceling with 30-hr battery.' },
  { hobby: 'Music', category: 'Headphones', brand: 'Sennheiser', product_name: 'Sennheiser Momentum 4 Wireless', price: 24990, image_url: 'https://m.media-amazon.com/images/I/61L18G2x4LL._SX679_.jpg', official_url: 'https://www.sennheiser-hearing.com/en-IN/p/momentum-4-wireless/', source_type: 'official_product_page', description: 'Audiophile wireless headphones with 60-hr battery.' },
  { hobby: 'Music', category: 'Headphones', brand: 'Beyerdynamic', product_name: 'Beyerdynamic DT 770 PRO 80Ω', price: 13999, image_url: 'https://m.media-amazon.com/images/I/711mYcKq4yL._SX679_.jpg', official_url: 'https://global.beyerdynamic.com/dt-770-pro.html', source_type: 'official_product_page', description: 'Closed-back studio monitor headphones.' },
  { hobby: 'Music', category: 'Headphones', brand: 'Audio-Technica', product_name: 'Audio-Technica ATH-M50x', price: 10999, image_url: 'https://m.media-amazon.com/images/I/71o8Q5XJS5L._SX679_.jpg', official_url: 'https://www.audio-technica.com/en-in/ath-m50x', source_type: 'official_product_page', description: 'Studio reference monitor headphones, legendary clarity.' },
  { hobby: 'Music', category: 'Headphones', brand: 'JBL', product_name: 'JBL Tune 770NC', price: 4999, image_url: 'https://m.media-amazon.com/images/I/61C4XOATAJL._SX679_.jpg', official_url: 'https://in.jbl.com/headphones/JBLTUNE770NCBLKAM.html', source_type: 'official_product_page', description: 'Adaptive noise canceling over-ear headphones.' },
  { hobby: 'Music', category: 'Headphones', brand: 'Marshall', product_name: 'Marshall Monitor II ANC', price: 19999, image_url: 'https://m.media-amazon.com/images/I/61KE+nFNhNL._SX679_.jpg', official_url: 'https://www.marshallheadphones.com/en_in/monitor-ii-a-n-c', source_type: 'official_product_page', description: 'Over-ear ANC headphones with iconic Marshall design.' },

  // -- SPEAKERS --
  { hobby: 'Music', category: 'Speakers', brand: 'JBL', product_name: 'JBL Flip 6', price: 11999, image_url: 'https://m.media-amazon.com/images/I/71PP-7x2QQL._SX679_.jpg', official_url: 'https://in.jbl.com/bluetooth-speakers/JBLFLIP6BLKAM.html', source_type: 'official_product_page', description: 'IP67 portable Bluetooth speaker with 12-hr battery.' },
  { hobby: 'Music', category: 'Speakers', brand: 'Marshall', product_name: 'Marshall Stanmore III Bluetooth', price: 39999, image_url: 'https://m.media-amazon.com/images/I/81u4L+LTFEL._SX679_.jpg', official_url: 'https://www.marshallheadphones.com/en_in/stanmore-iii-bluetooth', source_type: 'official_product_page', description: 'High-fidelity home speaker with iconic Marshall look.' },
  { hobby: 'Music', category: 'Speakers', brand: 'Edifier', product_name: 'Edifier R1280T Powered Bookshelf', price: 7499, image_url: 'https://m.media-amazon.com/images/I/61Rm3PzUCqL._SX679_.jpg', official_url: 'https://www.edifier.com/global/p/bookshelf-speakers/r1280t', source_type: 'official_product_page', description: '42W stereo active bookshelf speaker with dual RCA.' },
  { hobby: 'Music', category: 'Speakers', brand: 'Sony', product_name: 'Sony SRS-XB33 Portable Speaker', price: 8990, image_url: 'https://m.media-amazon.com/images/I/71wAFopnYuL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/speakers/srs-xb33', source_type: 'official_product_page', description: 'IP67 speaker with extra bass and 24-hr battery.' },
  { hobby: 'Music', category: 'Speakers', brand: 'Bose', product_name: 'Bose SoundLink Flex', price: 11900, image_url: 'https://m.media-amazon.com/images/I/61FMdMzYqBL._SX679_.jpg', official_url: 'https://www.bose.in/en_in/products/speakers/portable_speakers/soundlink-flex.html', source_type: 'official_product_page', description: 'Waterproof portable speaker with PositionIQ technology.' },

  // -- HIGH-RES PLAYERS --
  { hobby: 'Music', category: 'High-Res Players', brand: 'Fiio', product_name: 'Fiio M11S DAP', price: 34999, image_url: 'https://m.media-amazon.com/images/I/61BPNxjaBbL._SX679_.jpg', official_url: 'https://www.fiio.com/m11s', source_type: 'official_product_page', description: 'Android DAP with ES9038Q2M DAC and 5G Wi-Fi.' },
  { hobby: 'Music', category: 'High-Res Players', brand: 'Sony', product_name: 'Sony NW-A306 Walkman', price: 21990, image_url: 'https://m.media-amazon.com/images/I/71lEdMMm7IL._SX679_.jpg', official_url: 'https://www.sony.co.in/electronics/walkman-digital-players/nw-a306', source_type: 'official_product_page', description: 'Hi-Res Android Walkman with DSEE Ultimate AI upscaling.' },
  { hobby: 'Music', category: 'High-Res Players', brand: 'Shanling', product_name: 'Shanling M3 Ultra DAP', price: 21999, image_url: 'https://m.media-amazon.com/images/I/61iKf2fG5wL._SX679_.jpg', official_url: 'https://en.shanlingmusic.com/M3Ultra', source_type: 'official_product_page', description: 'Compact DAP with Snapdragon 665 and dual CS43198.' },

  // -- ACCESSORIES --
  { hobby: 'Music', category: 'Accessories', brand: 'SpinFit', product_name: 'SpinFit CP145 Ear Tips (3 Pairs)', price: 999, image_url: 'https://m.media-amazon.com/images/I/61rEJHSAq5L._SX679_.jpg', official_url: 'https://www.headphonezone.in/products/spinfit-cp145', source_type: 'distributor', description: 'Premium rotating silicone ear tips for IEMs.' },
  { hobby: 'Music', category: 'Accessories', brand: 'Dekoni', product_name: 'Dekoni Elite Sheepskin Pads for DT770', price: 4999, image_url: 'https://m.media-amazon.com/images/I/71XCVO6VdvL._SX679_.jpg', official_url: 'https://dekonilaudio.com/products/beyerdynamic-dt-series', source_type: 'official_product_page', description: 'Plush sheepskin leather ear pad upgrade.' },
  { hobby: 'Music', category: 'Accessories', brand: 'UGREEN', product_name: 'UGREEN USB-C to 3.5mm DAC Adapter', price: 1299, image_url: 'https://m.media-amazon.com/images/I/51BbvW6SILL._SX679_.jpg', official_url: 'https://www.ugreen.com/products/ugreen-usb-c-to-3-5mm-audio-adapter', source_type: 'official_product_page', description: 'Hi-Res 32-bit/384kHz USB-C audio adapter.' },

  // ================================================================
  // GAMING
  // ================================================================

  // -- GAMING KEYBOARDS --
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'Razer', product_name: 'Razer Huntsman V3 Pro TKL', price: 17499, image_url: 'https://m.media-amazon.com/images/I/71UVq8v6zGL._SX679_.jpg', official_url: 'https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro-tkl', source_type: 'official_product_page', description: 'Analog optical TKL keyboard with actuation precision.' },
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'Logitech G', product_name: 'Logitech G915 TKL Wireless', price: 16495, image_url: 'https://m.media-amazon.com/images/I/71BhCUJHWCL._SX679_.jpg', official_url: 'https://www.logitechg.com/en-in/products/gaming-keyboards/g915-tkl-wireless.html', source_type: 'official_product_page', description: 'Slim low-profile wireless gaming keyboard, LIGHTSPEED.' },
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'Keychron', product_name: 'Keychron Q3 Pro QMK', price: 12499, image_url: 'https://m.media-amazon.com/images/I/61NxWlb4BwL._SX679_.jpg', official_url: 'https://keychron.in/product/keychron-q3-pro-qmk-wireless-mechanical-keyboard/', source_type: 'official_product_page', description: 'Wireless 80% gasket-mount mechanical keyboard.' },
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'Corsair', product_name: 'Corsair K70 RGB Pro MX Red', price: 11999, image_url: 'https://m.media-amazon.com/images/I/71bv44pTbfL._SX679_.jpg', official_url: 'https://www.corsair.com/in/en/p/keyboards/ch-9109410-in/k70-rgb-pro-mechanical-gaming-keyboard', source_type: 'official_product_page', description: 'Full-size RGB gaming keyboard with Cherry MX Red.' },
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'HyperX', product_name: 'HyperX Alloy Origins 65', price: 7999, image_url: 'https://m.media-amazon.com/images/I/71A49r0YGNL._SX679_.jpg', official_url: 'https://www.hyperxgaming.com/in/keyboards/hyperx-alloy-origins-65-mechanical-gaming-keyboard', source_type: 'official_product_page', description: 'Compact 65% aluminum gaming keyboard.' },
  { hobby: 'Gaming', category: 'Gaming Keyboards', brand: 'Redragon', product_name: 'Redragon K552 Kumara TKL', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71d6ZPJbNtL._SX679_.jpg', official_url: 'https://redragon.in/products/k552-kumara', source_type: 'official_product_page', description: 'Budget TKL red-backlit mechanical keyboard.' },

  // -- GAMING MICE --
  { hobby: 'Gaming', category: 'Gaming Mice', brand: 'Logitech G', product_name: 'Logitech G Pro X Superlight 2', price: 15995, image_url: 'https://m.media-amazon.com/images/I/51Jky2JRF2L._SX679_.jpg', official_url: 'https://www.logitechg.com/en-in/products/gaming-mice/pro-x2-superlight.html', source_type: 'official_product_page', description: 'Ultra-lightweight 60g wireless esports mouse.' },
  { hobby: 'Gaming', category: 'Gaming Mice', brand: 'Razer', product_name: 'Razer DeathAdder V3 Pro', price: 13999, image_url: 'https://m.media-amazon.com/images/I/61Uf3n55Z1L._SX679_.jpg', official_url: 'https://www.razer.com/gaming-mice/razer-deathadder-v3-pro', source_type: 'official_product_page', description: 'Ergonomic wireless mouse with Focus Pro 30K sensor.' },
  { hobby: 'Gaming', category: 'Gaming Mice', brand: 'SteelSeries', product_name: 'SteelSeries Rival 650 Wireless', price: 7999, image_url: 'https://m.media-amazon.com/images/I/61lqBXERF-L._SX679_.jpg', official_url: 'https://steelseries.com/gaming-mice/rival-650-wireless', source_type: 'official_product_page', description: 'Fast 1ms wireless mouse with dual optical sensor.' },
  { hobby: 'Gaming', category: 'Gaming Mice', brand: 'Glorious', product_name: 'Glorious Model O 2 Wireless', price: 8999, image_url: 'https://m.media-amazon.com/images/I/61qy0eCPgNL._SX679_.jpg', official_url: 'https://www.gloriousgaming.com/products/model-o-2-wireless', source_type: 'official_product_page', description: 'Lightweight honeycomb wireless gaming mouse 59g.' },
  { hobby: 'Gaming', category: 'Gaming Mice', brand: 'Corsair', product_name: 'Corsair M75 AIR Wireless', price: 9999, image_url: 'https://m.media-amazon.com/images/I/61hV0U1kfNL._SX679_.jpg', official_url: 'https://www.corsair.com/in/en/p/gaming-mice/ch-9315011-ww/m75-air-wireless-ultra-lightweight-gaming-mouse', source_type: 'official_product_page', description: 'Ultra-light 60g wireless mouse with SLIPSTREAM.' },

  // -- GAMING HEADSETS --
  { hobby: 'Gaming', category: 'Gaming Headsets', brand: 'Razer', product_name: 'Razer BlackShark V2 Pro (2023)', price: 14999, image_url: 'https://m.media-amazon.com/images/I/61FXW9WKBYL._SX679_.jpg', official_url: 'https://www.razer.com/gaming-headsets/razer-blackshark-v2-pro', source_type: 'official_product_page', description: 'Wireless gaming headset with THX Spatial Audio.' },
  { hobby: 'Gaming', category: 'Gaming Headsets', brand: 'HyperX', product_name: 'HyperX Cloud Alpha Wireless', price: 14999, image_url: 'https://m.media-amazon.com/images/I/71bYOdm+aJL._SX679_.jpg', official_url: 'https://www.hyperxgaming.com/in/headsets/cloud-alpha-wireless-gaming-headset', source_type: 'official_product_page', description: '300-hour battery life wireless gaming headset.' },
  { hobby: 'Gaming', category: 'Gaming Headsets', brand: 'Logitech G', product_name: 'Logitech G733 LIGHTSPEED Wireless', price: 9995, image_url: 'https://m.media-amazon.com/images/I/71D0vVnMtIL._SX679_.jpg', official_url: 'https://www.logitechg.com/en-in/products/gaming-audio/g733-rgb-wireless-headset.html', source_type: 'official_product_page', description: 'Colorful LIGHTSPEED wireless headset with DTS 2.0.' },
  { hobby: 'Gaming', category: 'Gaming Headsets', brand: 'SteelSeries', product_name: 'SteelSeries Arctis Nova Pro Wireless', price: 27999, image_url: 'https://m.media-amazon.com/images/I/71wjJEnIkML._SX679_.jpg', official_url: 'https://steelseries.com/gaming-headsets/arctis-nova-pro-wireless', source_type: 'official_product_page', description: 'Premium wireless gaming headset with hot-swap battery.' },

  // -- CONTROLLERS --
  { hobby: 'Gaming', category: 'Controllers', brand: 'Xbox', product_name: 'Xbox Wireless Controller (Carbon Black)', price: 5590, image_url: 'https://m.media-amazon.com/images/I/61MPylIWx5L._SX679_.jpg', official_url: 'https://www.xbox.com/en-IN/accessories/controllers/wireless-controller', source_type: 'official_product_page', description: 'Ergonomic Xbox wireless controller for PC/console.' },
  { hobby: 'Gaming', category: 'Controllers', brand: '8BitDo', product_name: '8BitDo Ultimate Controller 2.4G', price: 4999, image_url: 'https://m.media-amazon.com/images/I/61F03TUZIXL._SX679_.jpg', official_url: 'https://www.8bitdo.com/ultimate-2/', source_type: 'official_product_page', description: 'Pro-grade PC controller with Hall Effect joysticks.' },
  { hobby: 'Gaming', category: 'Controllers', brand: 'Cosmic Byte', product_name: 'Cosmic Byte C3070W Nebula Wireless', price: 2599, image_url: 'https://m.media-amazon.com/images/I/71jT4e02hbL._SX679_.jpg', official_url: 'https://cosmicbyte.com/product/c3070w-nebula-wireless-gamepad/', source_type: 'official_product_page', description: 'Budget wireless gamepad for PC with 10-hr battery.' },
  { hobby: 'Gaming', category: 'Controllers', brand: 'Redgear', product_name: 'Redgear Pro Wireless Gamepad', price: 1999, image_url: 'https://m.media-amazon.com/images/I/71KoFDOmIHL._SX679_.jpg', official_url: 'https://redgeargaming.com/products/redgear-pro-wireless-gamepad', source_type: 'official_product_page', description: 'Plug-and-play wireless gamepad for PC gaming.' },

  // -- GAMING CHAIRS --
  { hobby: 'Gaming', category: 'Gaming Chairs', brand: 'Secretlab', product_name: 'Secretlab TITAN Evo 2022', price: 39999, image_url: 'https://m.media-amazon.com/images/I/61fALxqGakL._SX679_.jpg', official_url: 'https://secretlab.co/collections/titan-gaming-chairs', source_type: 'official_product_page', description: 'Premium hybrid leatherette gaming chair with lumbar.' },
  { hobby: 'Gaming', category: 'Gaming Chairs', brand: 'Green Soul', product_name: 'Green Soul Monster Ultimate Series', price: 14999, image_url: 'https://m.media-amazon.com/images/I/81a7mCZY1BL._SX679_.jpg', official_url: 'https://greensoulgaming.com/products/monster-ultimate', source_type: 'official_product_page', description: 'Ergonomic gaming chair with 4D armrests.' },
  { hobby: 'Gaming', category: 'Gaming Chairs', brand: 'AndaSeat', product_name: 'AndaSeat Kaiser 3 XL Gaming Chair', price: 29999, image_url: 'https://m.media-amazon.com/images/I/71PVNPzXY+L._SX679_.jpg', official_url: 'https://www.andaseat.com/collections/gaming-chairs/products/kaiser-series-3-gaming-chair', source_type: 'official_product_page', description: 'XL size gaming chair with magnetic headrest pillow.' },

  // -- MONITORS --
  { hobby: 'Gaming', category: 'Monitors', brand: 'ASUS ROG', product_name: 'ASUS ROG Swift 27" 165Hz QHD', price: 34999, image_url: 'https://m.media-amazon.com/images/I/81YRFfK3E4L._SX679_.jpg', official_url: 'https://rog.asus.com/monitors/27-to-31-5-inches/rog-swift-pg27q-model/', source_type: 'official_product_page', description: '27" QHD 165Hz IPS gaming monitor with G-Sync.' },
  { hobby: 'Gaming', category: 'Monitors', brand: 'LG', product_name: 'LG UltraGear 27GP850-B 180Hz', price: 27999, image_url: 'https://m.media-amazon.com/images/I/71YyMtyfF-L._SX679_.jpg', official_url: 'https://www.lg.com/in/monitors/lg-27gp850-b', source_type: 'official_product_page', description: '27" QHD Nano IPS gaming monitor, 1ms GtG.' },
  { hobby: 'Gaming', category: 'Monitors', brand: 'Samsung', product_name: 'Samsung Odyssey G5 27" 165Hz', price: 22999, image_url: 'https://m.media-amazon.com/images/I/71R+TGUF2GL._SX679_.jpg', official_url: 'https://www.samsung.com/in/monitors/gaming/odyssey-g5-27-inch-165hz-1ms-lc27g55tqwwxxl/', source_type: 'official_product_page', description: '27" curved QHD 165Hz gaming monitor with HDR10.' },
  { hobby: 'Gaming', category: 'Monitors', brand: 'Acer Predator', product_name: 'Acer Predator XB271H 27" 165Hz', price: 29999, image_url: 'https://m.media-amazon.com/images/I/81+LorS2iiL._SX679_.jpg', official_url: 'https://www.acer.com/in-en/predator/monitors', source_type: 'official_brand_page', description: '27" FHD IPS gaming monitor with NVIDIA G-Sync.' },
  { hobby: 'Gaming', category: 'Monitors', brand: 'BenQ', product_name: 'BenQ ZOWIE XL2411K 24" 144Hz', price: 21999, image_url: 'https://m.media-amazon.com/images/I/61bE-Wy3RIL._SX679_.jpg', official_url: 'https://zowie.benq.com/en-in/monitor/xl2411k.html', source_type: 'official_product_page', description: 'Esports monitor with DyAc+, built for CS/Valorant.' },

  // ================================================================
  // FOOTBALL
  // ================================================================

  // -- FOOTBALL BOOTS --
  { hobby: 'Football', category: 'Football Boots', brand: 'Nike', product_name: 'Nike Phantom GX Elite FG', price: 22995, image_url: 'https://m.media-amazon.com/images/I/61xXm5mHIfL._SX679_.jpg', official_url: 'https://www.nike.com/in/t/phantom-gx-elite-fg-football-boot', source_type: 'official_product_page', description: 'Precision control boots with Gripknit upper.' },
  { hobby: 'Football', category: 'Football Boots', brand: 'Adidas', product_name: 'Adidas Predator Accuracy.1 FG', price: 19999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/25ea947ce4044b7e9b0eaf95010642fa_9366/Predator_Accuracy.1_Firm_Ground_Boots_White_GZ0038_22_model.jpg', official_url: 'https://www.adidas.co.in/predator-accuracy.1-firm-ground-boots/GZ0038.html', source_type: 'official_product_page', description: 'Controlframe outsole with precision strap control.' },
  { hobby: 'Football', category: 'Football Boots', brand: 'Puma', product_name: 'Puma King Ultimate FG/AG', price: 17999, image_url: 'https://m.media-amazon.com/images/I/51E7XGdEd1L._SX679_.jpg', official_url: 'https://in.puma.com/in/en/pd/king-ultimate-fgag-football-boots/107563_01.html', source_type: 'official_product_page', description: 'Iconic King boot reborn in K-leather for firm ground.' },
  { hobby: 'Football', category: 'Football Boots', brand: 'Nivia', product_name: 'Nivia Carbonite 9.0 Football Shoes', price: 2199, image_url: 'https://m.media-amazon.com/images/I/71TpFY4NkLL._SX679_.jpg', official_url: 'https://nivia.com/product/carbonite-9/', source_type: 'official_product_page', description: 'Budget firm-ground football boots, synthetic upper.' },

  // -- FOOTBALLS --
  { hobby: 'Football', category: 'Footballs', brand: 'Adidas', product_name: 'Adidas Tiro Club Football', price: 999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a93b64eb09a64c2baa35ae7800d80e11_9366/Tiro_Club_Ball_White_HT2975_01_standard.jpg', official_url: 'https://www.adidas.co.in/tiro-club-ball/HT2975.html', source_type: 'official_product_page', description: 'Machine-stitched training ball, FIFA Basic approved.' },
  { hobby: 'Football', category: 'Footballs', brand: 'Nike', product_name: 'Nike Academy Football', price: 1295, image_url: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b55bae07-b3b4-45b2-b5a9-8edff7455e4b/academy-football-dh9sZl.png', official_url: 'https://www.nike.com/in/t/academy-football', source_type: 'official_product_page', description: 'Durable machine-stitched training ball.' },
  { hobby: 'Football', category: 'Footballs', brand: 'Nivia', product_name: 'Nivia Storm Football Size 5', price: 699, image_url: 'https://m.media-amazon.com/images/I/71XUZK+rEWL._SX679_.jpg', official_url: 'https://nivia.com/product/storm/', source_type: 'official_product_page', description: 'Machine-stitched nylon wound football, all surfaces.' },
  { hobby: 'Football', category: 'Footballs', brand: 'Cosco', product_name: 'Cosco Brazil Football Size 5', price: 549, image_url: 'https://m.media-amazon.com/images/I/61n9R2ZIjML._SX679_.jpg', official_url: 'https://www.amazon.in/Cosco-Brazil-Football/dp/B00KUB4P0M', source_type: 'distributor', description: 'Rubber carcass training football for all surfaces.' },

  // -- JERSEYS --
  { hobby: 'Football', category: 'Jerseys', brand: 'Nike', product_name: 'India National Team Home Jersey 2023', price: 4299, image_url: 'https://m.media-amazon.com/images/I/71YNjhP0eNL._SX679_.jpg', official_url: 'https://www.nike.com/in/t/india-2023-24-stadium-home-football-shirt', source_type: 'official_product_page', description: 'Official Dri-FIT India football jersey.' },
  { hobby: 'Football', category: 'Jerseys', brand: 'Adidas', product_name: 'FC Barcelona Home Jersey 2024-25', price: 6999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/bfcce77826cb4c7cbf00aef100ae4bb8_9366/FC_Barcelona_24-25_Home_Jersey_Red_IQ0491_HM1.jpg', official_url: 'https://www.adidas.co.in/fc-barcelona-24-25-home-jersey/IQ0491.html', source_type: 'official_product_page', description: 'Official FCB home jersey with HEAT.RDY technology.' },
  { hobby: 'Football', category: 'Jerseys', brand: 'Adidas', product_name: 'Real Madrid Away Jersey 2024-25', price: 6999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4fd7c0b432aa4f3eb765af120102e7e5_9366/Real_Madrid_24-25_Away_Jersey_Purple_IX7593_HM1.jpg', official_url: 'https://www.adidas.co.in/real-madrid-24-25-away-jersey/IX7593.html', source_type: 'official_product_page', description: 'Official Real Madrid away jersey, AEROREADY fabric.' },

  // -- TRAINING EQUIPMENT --
  { hobby: 'Football', category: 'Training Equipment', brand: 'Nivia', product_name: 'Nivia Marker Cones Set of 50', price: 599, image_url: 'https://m.media-amazon.com/images/I/71bSzJDr3ML._SX679_.jpg', official_url: 'https://nivia.com/product/marker-cones/', source_type: 'official_product_page', description: 'Durable plastic training cones for agility drills.' },
  { hobby: 'Football', category: 'Training Equipment', brand: 'Adidas', product_name: 'Adidas Pro Training Bibs (Set of 5)', price: 1999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d2ed0699a51b4ae89bd5af2d010e08e7_9366/Pro_Training_Mesh_Bib_Red_HT9913_01_standard.jpg', official_url: 'https://www.adidas.co.in/pro-training-mesh-bib/HT9913.html', source_type: 'official_product_page', description: 'Lightweight mesh training bibs for team practice.' },
  { hobby: 'Football', category: 'Training Equipment', brand: 'Kipsta', product_name: 'Kipsta Adjustable Training Ladder', price: 999, image_url: 'https://contents.mediadecathlon.com/p2257898/k$a58f2c0b63ba58ee4bd42abc5bb88a1e/agility-ladder-football-training-ladder.jpg', official_url: 'https://www.decathlon.in/p/8595776/agility-ladder-football-training-ladder', source_type: 'official_product_page', description: '6m agility ladder for footwork and speed training.' },

  // -- GOALKEEPER GEAR --
  { hobby: 'Football', category: 'Goalkeeper Gear', brand: 'Reusch', product_name: 'Reusch Attrakt Silver NC', price: 3999, image_url: 'https://m.media-amazon.com/images/I/71eRaHcpMyL._SX679_.jpg', official_url: 'https://www.reusch.com/en/goalkeeper-gloves/attrakt-silver-nc/', source_type: 'official_product_page', description: 'Pro-level GK gloves with Negative Cut and foam.' },
  { hobby: 'Football', category: 'Goalkeeper Gear', brand: 'Uhlsport', product_name: 'Uhlsport Hyperact Absolutgrip', price: 5499, image_url: 'https://m.media-amazon.com/images/I/61bScSMbQlL._SX679_.jpg', official_url: 'https://www.uhlsport.com/en/goalkeeping/gloves/hyperact', source_type: 'official_product_page', description: 'Tournament GK gloves with Absolutgrip HN foam.' },
  { hobby: 'Football', category: 'Goalkeeper Gear', brand: 'Nivia', product_name: 'Nivia Simbolo Goalkeeper Gloves', price: 899, image_url: 'https://m.media-amazon.com/images/I/61dBDhCRc5L._SX679_.jpg', official_url: 'https://nivia.com/product/simbolo/', source_type: 'official_product_page', description: 'Budget training GK gloves with latex palm.' },

  // ================================================================
  // CODING
  // ================================================================

  // -- LAPTOPS --
  { hobby: 'Coding', category: 'Laptops', brand: 'Apple', product_name: 'MacBook Pro 14" M3 Pro', price: 199900, image_url: 'https://m.media-amazon.com/images/I/61vFO3R5UNL._SX679_.jpg', official_url: 'https://www.apple.com/in/macbook-pro/', source_type: 'official_product_page', description: 'M3 Pro chip, 18GB RAM, Liquid Retina XDR display.' },
  { hobby: 'Coding', category: 'Laptops', brand: 'Dell', product_name: 'Dell XPS 15 (2024)', price: 185000, image_url: 'https://m.media-amazon.com/images/I/71p0Wf84LqL._SX679_.jpg', official_url: 'https://www.dell.com/en-in/shop/dell-laptops/xps-15-laptop/spd/xps-15-9530-laptop', source_type: 'official_product_page', description: 'Intel i9, 32GB RAM, OLED 3.5K display creator laptop.' },
  { hobby: 'Coding', category: 'Laptops', brand: 'ASUS', product_name: 'ASUS VivoBook Pro 16 OLED', price: 89990, image_url: 'https://m.media-amazon.com/images/I/71cGVKy63rL._SX679_.jpg', official_url: 'https://www.asus.com/in/laptops/for-home/vivobook/vivobook-pro-16-oled-k6602/', source_type: 'official_product_page', description: 'Ryzen 9 + RTX 4060, OLED ProArt display.' },
  { hobby: 'Coding', category: 'Laptops', brand: 'Lenovo', product_name: 'Lenovo ThinkPad X1 Carbon Gen 12', price: 169000, image_url: 'https://m.media-amazon.com/images/I/41EuaGbUCiL._SX679_.jpg', official_url: 'https://www.lenovo.com/in/en/laptops/thinkpad/thinkpad-x1/x1-carbon-gen-12/p/21KCCTO1WWINEN1', source_type: 'official_product_page', description: 'Ultra-thin business laptop, Intel vPro, 32GB RAM.' },
  { hobby: 'Coding', category: 'Laptops', brand: 'HP', product_name: 'HP Dev One (Dev Edition)', price: 114999, image_url: 'https://m.media-amazon.com/images/I/61PiqLh5FBL._SX679_.jpg', official_url: 'https://www.hp.com/in-en/laptops/', source_type: 'official_brand_page', description: 'Linux-first developer laptop with AMD Ryzen 7 PRO.' },

  // -- KEYBOARDS (Coding) --
  { hobby: 'Coding', category: 'Keyboards', brand: 'Keychron', product_name: 'Keychron K2 V2 Wireless', price: 8499, image_url: 'https://m.media-amazon.com/images/I/61QG3aNf+HL._SX679_.jpg', official_url: 'https://keychron.in/product/keychron-k2-wireless-mechanical-keyboard/', source_type: 'official_product_page', description: '75% wireless mechanical keyboard, hot-swappable.' },
  { hobby: 'Coding', category: 'Keyboards', brand: 'Logitech', product_name: 'Logitech MX Keys for Mac', price: 9995, image_url: 'https://m.media-amazon.com/images/I/61MnHrC6u1L._SX679_.jpg', official_url: 'https://www.logitech.com/en-in/products/keyboards/mx-keys-for-mac.html', source_type: 'official_product_page', description: 'Smart illuminated wireless keyboard for Mac.' },
  { hobby: 'Coding', category: 'Keyboards', brand: 'Royal Kludge', product_name: 'Royal Kludge RK96 Wireless', price: 5499, image_url: 'https://m.media-amazon.com/images/I/71CqopMPm7L._SX679_.jpg', official_url: 'https://rkgamingstore.com/products/rk96-wireless-mechanical-keyboard', source_type: 'official_product_page', description: '96% hot-swap wireless mechanical keyboard.' },
  { hobby: 'Coding', category: 'Keyboards', brand: 'Redragon', product_name: 'Redragon K617 Fizz 60% RGB', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71O+W4p8x9L._SX679_.jpg', official_url: 'https://redragon.in/products/k617-fizz-60-wired-rgb-gaming-keyboard', source_type: 'official_product_page', description: 'Compact 60% hot-swappable mechanical keyboard.' },

  // -- MICE (Coding) --
  { hobby: 'Coding', category: 'Mice', brand: 'Logitech', product_name: 'Logitech MX Master 3S for Mac', price: 9995, image_url: 'https://m.media-amazon.com/images/I/71sVxpjGCDL._SX679_.jpg', official_url: 'https://www.logitech.com/en-in/products/mice/mx-master-3s-mac-wireless-mouse.html', source_type: 'official_product_page', description: 'Ergonomic wireless productivity mouse, 8K DPI.' },
  { hobby: 'Coding', category: 'Mice', brand: 'Logitech', product_name: 'Logitech MX Anywhere 3S', price: 5495, image_url: 'https://m.media-amazon.com/images/I/617Ks7gQF3L._SX679_.jpg', official_url: 'https://www.logitech.com/en-in/products/mice/mx-anywhere-3s.html', source_type: 'official_product_page', description: 'Compact wireless mouse, works on any surface.' },
  { hobby: 'Coding', category: 'Mice', brand: 'Razer', product_name: 'Razer Pro Click Wireless Mouse', price: 6995, image_url: 'https://m.media-amazon.com/images/I/61Jh6GDWVTL._SX679_.jpg', official_url: 'https://www.razer.com/productivity-mice/razer-pro-click', source_type: 'official_product_page', description: 'Productivity wireless mouse with Humanscale design.' },

  // -- MONITORS (Coding) --
  { hobby: 'Coding', category: 'Monitors', brand: 'LG', product_name: 'LG 34WP65C-B 34" Ultrawide', price: 34500, image_url: 'https://m.media-amazon.com/images/I/71YyMtyfF-L._SX679_.jpg', official_url: 'https://www.lg.com/in/monitors/lg-34wp65c-b', source_type: 'official_product_page', description: '34" curved ultrawide QHD IPS monitor.' },
  { hobby: 'Coding', category: 'Monitors', brand: 'Dell', product_name: 'Dell U2723D UltraSharp 27" 4K', price: 49999, image_url: 'https://m.media-amazon.com/images/I/61c5YXQX1ML._SX679_.jpg', official_url: 'https://www.dell.com/en-in/shop/dell-ultrasharp-27-4k-usb-c-hub-monitor-u2723de/apd/210-bdpg/monitors-monitor-accessories', source_type: 'official_product_page', description: '27" 4K USB-C hub monitor with IPS Black panel.' },
  { hobby: 'Coding', category: 'Monitors', brand: 'Samsung', product_name: 'Samsung ViewFinity S8 32" 4K', price: 42999, image_url: 'https://m.media-amazon.com/images/I/61R+-bRoTTL._SX679_.jpg', official_url: 'https://www.samsung.com/in/monitors/high-resolution/viewfinity-s8-32-4k-uhd-ls32b800pxwxxl/', source_type: 'official_product_page', description: '32" 4K UHD IPS monitor with USB-C 90W power delivery.' },
  { hobby: 'Coding', category: 'Monitors', brand: 'BenQ', product_name: 'BenQ PD2725U 27" 4K Designer Monitor', price: 54999, image_url: 'https://m.media-amazon.com/images/I/71SXmxC-FLL._SX679_.jpg', official_url: 'https://www.benq.com/en-in/monitor/programming/pd2725u.html', source_type: 'official_product_page', description: '27" 4K IPS Thunderbolt 4 monitor for developers.' },

  // -- DESK ACCESSORIES --
  { hobby: 'Coding', category: 'Desk Accessories', brand: 'UGREEN', product_name: 'UGREEN 100W GaN Charger (4-in-1)', price: 3499, image_url: 'https://m.media-amazon.com/images/I/61JbVkqVGdL._SX679_.jpg', official_url: 'https://www.ugreen.com/products/ugreen-100w-4-port-gan-fast-charger', source_type: 'official_product_page', description: 'Compact 100W GaN charger with 4 ports for laptop+.' },
  { hobby: 'Coding', category: 'Desk Accessories', brand: 'Portronics', product_name: 'Portronics Mport 7 USB-C Hub', price: 2499, image_url: 'https://m.media-amazon.com/images/I/71-Z9Y9m57L._SX679_.jpg', official_url: 'https://www.portronics.com/products/mport-7', source_type: 'official_product_page', description: '7-in-1 USB-C hub with 4K HDMI, SD, USB-A.' },
  { hobby: 'Coding', category: 'Desk Accessories', brand: 'DailyObjects', product_name: 'DailyObjects StudioFlex Laptop Stand', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71BEjNcv-KL._SX679_.jpg', official_url: 'https://www.dailyobjects.com/products/studioflex-laptop-stand', source_type: 'official_product_page', description: 'Ergonomic aluminum adjustable laptop stand.' },
  { hobby: 'Coding', category: 'Desk Accessories', brand: 'Zebronics', product_name: 'Zebronics ZEB-120HPS USB Hub', price: 849, image_url: 'https://m.media-amazon.com/images/I/61T8VY6bj4L._SX679_.jpg', official_url: 'https://zebronics.com/products/zeb-120hps', source_type: 'official_product_page', description: '4-port USB 3.0 hub with power switch.' },

  // -- BOOKS & LEARNING --
  { hobby: 'Coding', category: 'Books & Learning', brand: 'No Starch Press', product_name: 'The Linux Command Line (2nd Ed)', price: 2499, image_url: 'https://m.media-amazon.com/images/I/51LDLVJ0e5L._SX679_.jpg', official_url: 'https://nostarch.com/tlcl2', source_type: 'official_product_page', description: 'The definitive guide to the Linux command line.' },
  { hobby: 'Coding', category: 'Books & Learning', brand: 'O\'Reilly', product_name: 'Learning Python (5th Ed)', price: 3499, image_url: 'https://m.media-amazon.com/images/I/51WmE5GPNXL._SX679_.jpg', official_url: 'https://www.oreilly.com/library/view/learning-python-5th/9781449355722/', source_type: 'official_product_page', description: 'Comprehensive Python programming guide by Mark Lutz.' },
  { hobby: 'Coding', category: 'Books & Learning', brand: 'Manning', product_name: 'Grokking Algorithms (2nd Ed)', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71JKVcFvM4L._SX679_.jpg', official_url: 'https://www.manning.com/books/grokking-algorithms-second-edition', source_type: 'official_product_page', description: 'Illustrated guide to algorithms for programmers.' },

  // ================================================================
  // ART & CRAFT
  // ================================================================

  // -- SKETCHBOOKS --
  { hobby: 'Art & Craft', category: 'Sketchbooks', brand: 'Brustro', product_name: 'Brustro Artist Sketchbook A4 200gsm', price: 649, image_url: 'https://m.media-amazon.com/images/I/71qL2RVm-5L._SX679_.jpg', official_url: 'https://www.amazon.in/Brustro-Artists-Sketchbook-180-Sheets/dp/B07PGPWB5C', source_type: 'distributor', description: 'Professional 200gsm acid-free cotton sketchbook.' },
  { hobby: 'Art & Craft', category: 'Sketchbooks', brand: 'Canson', product_name: 'Canson Universal Sketch Book A4', price: 899, image_url: 'https://m.media-amazon.com/images/I/71Z1-OFlz9L._SX679_.jpg', official_url: 'https://www.canson.com/en/art-books/universal-sketchbook', source_type: 'official_product_page', description: 'Universal sketchbook for pencil, charcoal, and markers.' },
  { hobby: 'Art & Craft', category: 'Sketchbooks', brand: 'Strathmore', product_name: 'Strathmore 400 Series Wirebound Sketch', price: 1299, image_url: 'https://m.media-amazon.com/images/I/81e4J0ky7DL._SX679_.jpg', official_url: 'https://www.strathmoreartist.com/product-category/400-series-sketch/', source_type: 'official_product_page', description: '60-sheet spiral wirebound sketchbook, 89gsm.' },

  // -- PAINTS --
  { hobby: 'Art & Craft', category: 'Paints', brand: 'Winsor & Newton', product_name: 'Winsor & Newton Cotman Watercolor 24-Pan', price: 1899, image_url: 'https://m.media-amazon.com/images/I/71Jq9i7lKAL._SX679_.jpg', official_url: 'https://www.winsornewton.com/row/explore/products/cotman-water-colours/cotman-water-colours-studio-sets-tin-24-half-pan-set/', source_type: 'official_product_page', description: '24 half-pan watercolor set in a metal tin.' },
  { hobby: 'Art & Craft', category: 'Paints', brand: 'Camlin', product_name: 'Camlin Artist Acrylic Color 12-Tube Set', price: 549, image_url: 'https://m.media-amazon.com/images/I/71h1xUY2mWL._SX679_.jpg', official_url: 'https://www.amazon.in/Camlin-Kokuyo-Artist-Acrylic-Colours/dp/B08JG3B6C3', source_type: 'distributor', description: '12 x 20ml artist acrylic color tubes.' },
  { hobby: 'Art & Craft', category: 'Paints', brand: 'Brustro', product_name: 'Brustro Professional Watercolors 36 Half Pans', price: 1499, image_url: 'https://m.media-amazon.com/images/I/71Z4Nl0PFZL._SX679_.jpg', official_url: 'https://www.amazon.in/Brustro-Professional-Watercolours-36-Pan/dp/B07PGR4QS3', source_type: 'distributor', description: 'Artist-grade watercolors with lightfast pigments.' },
  { hobby: 'Art & Craft', category: 'Paints', brand: 'Faber-Castell', product_name: 'Faber-Castell Creative Studio Acrylic Set', price: 999, image_url: 'https://m.media-amazon.com/images/I/71YMFrqETbL._SX679_.jpg', official_url: 'https://www.faber-castell.in/products/acrylic-colours', source_type: 'official_brand_page', description: '12 x 20ml studio acrylic paint set for beginners.' },

  // -- BRUSHES --
  { hobby: 'Art & Craft', category: 'Brushes', brand: 'Princeton', product_name: 'Princeton Heritage Watercolor Brush Set', price: 1299, image_url: 'https://m.media-amazon.com/images/I/71mIeBRDXOL._SX679_.jpg', official_url: 'https://www.princetonbrush.com/heritage-series-4050.html', source_type: 'official_product_page', description: 'Synthetic Kolinsky sable watercolor brush set.' },
  { hobby: 'Art & Craft', category: 'Brushes', brand: 'Camlin', product_name: 'Camlin Kokuyo Series 56 Round Brushes', price: 349, image_url: 'https://m.media-amazon.com/images/I/71a4V8K7NRL._SX679_.jpg', official_url: 'https://www.amazon.in/Camlin-Kokuyo-Series-Round-Brushes/dp/B00IQZYRGA', source_type: 'distributor', description: '7-piece artist brush set, series 56, round and flat.' },
  { hobby: 'Art & Craft', category: 'Brushes', brand: 'Brustro', product_name: 'Brustro Synthetics Brush Set (12-Piece)', price: 799, image_url: 'https://m.media-amazon.com/images/I/71nAkIjS8jL._SX679_.jpg', official_url: 'https://www.amazon.in/Brustro-Synthetic-Brush-Set-12/dp/B07SZ6XWGM', source_type: 'distributor', description: 'Long handle synthetic brushes for acrylic/oil.' },

  // -- PENCILS & MARKERS --
  { hobby: 'Art & Craft', category: 'Pencils & Markers', brand: 'Faber-Castell', product_name: 'Faber-Castell 9000 Art Set Tin 12', price: 899, image_url: 'https://m.media-amazon.com/images/I/61Uf3bpDmLL._SX679_.jpg', official_url: 'https://www.faber-castell.in/products/sketch-pencils-9000', source_type: 'official_product_page', description: 'Premium graphite pencil set with grades 2H to 8B.' },
  { hobby: 'Art & Craft', category: 'Pencils & Markers', brand: 'Staedtler', product_name: 'Staedtler Mars Lumograph 24-Pencil Set', price: 1399, image_url: 'https://m.media-amazon.com/images/I/71sUgb+C2nL._SX679_.jpg', official_url: 'https://www.staedtler.com/en/products/products-for-artists-and-crafters/drawing-sketching/mars-lumograph-pencils/', source_type: 'official_product_page', description: 'Break-resistant graphite pencils, artist quality.' },
  { hobby: 'Art & Craft', category: 'Pencils & Markers', brand: 'Copic', product_name: 'Copic Sketch 12-Marker Starter Set', price: 3999, image_url: 'https://m.media-amazon.com/images/I/71qSWTLjJZL._SX679_.jpg', official_url: 'https://copic.jp/en/product/sketch/', source_type: 'official_product_page', description: 'Professional refillable alcohol-based art markers.' },
  { hobby: 'Art & Craft', category: 'Pencils & Markers', brand: 'Sakura', product_name: 'Sakura Pigma Micron Pen Set (8 Sizes)', price: 999, image_url: 'https://m.media-amazon.com/images/I/71ydvBn9L3L._SX679_.jpg', official_url: 'https://www.sakuraofamerica.com/product/pigma-micron/', source_type: 'official_product_page', description: 'Archival pigment ink fine-line pens, waterproof.' },

  // -- CRAFT TOOLS --
  { hobby: 'Art & Craft', category: 'Craft Tools', brand: 'Fevicryl', product_name: 'Fevicryl Fabric Painting Kit', price: 499, image_url: 'https://m.media-amazon.com/images/I/81XGBrGERML._SX679_.jpg', official_url: 'https://www.amazon.in/Fevicryl-Fabric-Painting-Kit/dp/B07L7CPDW5', source_type: 'distributor', description: 'Complete fabric painting kit with 6 colors and brushes.' },
  { hobby: 'Art & Craft', category: 'Craft Tools', brand: 'Doms', product_name: 'Doms Craft Scissors & Cutter Set', price: 299, image_url: 'https://m.media-amazon.com/images/I/71mIqXiH1KL._SX679_.jpg', official_url: 'https://domsindia.com/craft', source_type: 'official_brand_page', description: 'Precision scissor and cutter set for paper crafts.' },

  // ================================================================
  // FITNESS
  // ================================================================

  // -- DUMBBELLS & WEIGHTS --
  { hobby: 'Fitness', category: 'Dumbbells & Weights', brand: 'Boldfit', product_name: 'Boldfit Hex Dumbbells 5kg Pair', price: 2199, image_url: 'https://m.media-amazon.com/images/I/71rVlYm7bTL._SX679_.jpg', official_url: 'https://boldfit.in/products/hex-dumbbells-set', source_type: 'official_brand_page', description: 'Rubber-coated hex dumbbells, pair.' },
  { hobby: 'Fitness', category: 'Dumbbells & Weights', brand: 'Kore', product_name: 'Kore PVC 20kg Home Gym Set', price: 3499, image_url: 'https://m.media-amazon.com/images/I/71GrSJ3nYlL._SX679_.jpg', official_url: 'https://www.amazon.in/Kore-Home-Gym-Set-20kg/dp/B07MYVHGCW', source_type: 'distributor', description: '20kg PVC weight set with rod and gloves.' },
  { hobby: 'Fitness', category: 'Dumbbells & Weights', brand: 'Lifelong', product_name: 'Lifelong LLFHGS60 Adjustable Dumbbell 10kg', price: 1999, image_url: 'https://m.media-amazon.com/images/I/71hBiaxH9nL._SX679_.jpg', official_url: 'https://lifelong.in/products/dumbbells', source_type: 'official_brand_page', description: 'Adjustable screw-type dumbbell with weight plates.' },
  { hobby: 'Fitness', category: 'Dumbbells & Weights', brand: 'Cockatoo', product_name: 'Cockatoo CFD-5 Rubber Coated Dumbbell 8kg', price: 1699, image_url: 'https://m.media-amazon.com/images/I/71Xe2GH1v1L._SX679_.jpg', official_url: 'https://www.amazon.in/Cockatoo-Rubber-Coated-Dumbbells/dp/B0812WCDPC', source_type: 'distributor', description: 'Fixed rubber dumbbell, anti-roll hex design.' },

  // -- RESISTANCE BANDS --
  { hobby: 'Fitness', category: 'Resistance Bands', brand: 'Boldfit', product_name: 'Boldfit Resistance Band Set (5 Levels)', price: 999, image_url: 'https://m.media-amazon.com/images/I/71Kj3lqBfQL._SX679_.jpg', official_url: 'https://boldfit.in/products/resistance-bands', source_type: 'official_brand_page', description: '5-level resistance loop bands for home workouts.' },
  { hobby: 'Fitness', category: 'Resistance Bands', brand: 'Decathlon', product_name: 'Decathlon Domyos Resistance Band 15kg', price: 849, image_url: 'https://contents.mediadecathlon.com/p2239124/k$6f6c8ecc73c3d396f8d8c1e5e9f7b3d1/resistance-band-easy-15-kg.jpg', official_url: 'https://www.decathlon.in/p/8777624/resistance-band-easy-15-kg', source_type: 'official_product_page', description: 'Heavy-duty flat resistance band for strength training.' },
  { hobby: 'Fitness', category: 'Resistance Bands', brand: 'Fitkit', product_name: 'Fitkit FT102 Tube Resistance Band Set', price: 699, image_url: 'https://m.media-amazon.com/images/I/71qWr-FXNML._SX679_.jpg', official_url: 'https://www.amazon.in/Fitkit-Resistance-Tube-Band-Set/dp/B07H82BZ6T', source_type: 'distributor', description: '5 resistance levels with door anchor and handles.' },

  // -- YOGA MATS --
  { hobby: 'Fitness', category: 'Yoga Mats', brand: 'Decathlon', product_name: 'Decathlon Comfort 8mm Yoga Mat', price: 1199, image_url: 'https://contents.mediadecathlon.com/p2246785/k$d62d84e43c2b3a5c3c35ae7d5b7d8e99/8mm-yoga-mat-comfort.jpg', official_url: 'https://www.decathlon.in/p/8788498/8-mm-comfort-yoga-mat', source_type: 'official_product_page', description: '8mm comfort foam yoga mat with carry strap.' },
  { hobby: 'Fitness', category: 'Yoga Mats', brand: 'Boldfit', product_name: 'Boldfit Premium EVA Yoga Mat 6mm', price: 799, image_url: 'https://m.media-amazon.com/images/I/71a3lNX7AHL._SX679_.jpg', official_url: 'https://boldfit.in/products/yoga-mat', source_type: 'official_brand_page', description: 'Non-slip 6mm EVA yoga mat with alignment lines.' },
  { hobby: 'Fitness', category: 'Yoga Mats', brand: 'Strauss', product_name: 'Strauss Anti-Skid Yoga Mat 6mm', price: 899, image_url: 'https://m.media-amazon.com/images/I/71sQlhI6QEL._SX679_.jpg', official_url: 'https://www.amazon.in/Strauss-Anti-Skid-Yoga-Mat/dp/B01MQ5NKGG', source_type: 'distributor', description: 'Premium EVA anti-skid yoga mat with carry bag.' },

  // -- GYM BAGS --
  { hobby: 'Fitness', category: 'Gym Bags', brand: 'Nike', product_name: 'Nike Brasilia 9.5 Training Duffel', price: 2995, image_url: 'https://m.media-amazon.com/images/I/71+M6pYXfrL._SX679_.jpg', official_url: 'https://www.nike.com/in/t/brasilia-9-5-training-duffel-bag-medium-30l', source_type: 'official_product_page', description: '41L training duffel with wet/dry storage pocket.' },
  { hobby: 'Fitness', category: 'Gym Bags', brand: 'Puma', product_name: 'Puma Phase Sports Bag', price: 1999, image_url: 'https://m.media-amazon.com/images/I/71bGSlY2dKL._SX679_.jpg', official_url: 'https://in.puma.com/in/en/pd/phase-sports-bag/079949.html', source_type: 'official_product_page', description: 'Compact gym bag with main compartment and side pocket.' },
  { hobby: 'Fitness', category: 'Gym Bags', brand: 'Adidas', product_name: 'Adidas Linear Duffel Bag M', price: 2499, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c5eebb5b14644ad89019aeec00e4e6af_9366/Linear_Duffel_Bag_M_Black_HT4742_01_00_standard.jpg', official_url: 'https://www.adidas.co.in/linear-duffel-bag-m/HT4742.html', source_type: 'official_product_page', description: 'Medium duffel bag with ventilated shoe pouch.' },

  // -- SHAKERS & BOTTLES --
  { hobby: 'Fitness', category: 'Shakers & Bottles', brand: 'Boldfit', product_name: 'Boldfit Cyclone Shaker Bottle 700ml', price: 499, image_url: 'https://m.media-amazon.com/images/I/71cKtCWLGTL._SX679_.jpg', official_url: 'https://boldfit.in/products/shaker-bottle', source_type: 'official_brand_page', description: 'Leak-proof cyclone shaker with storage compartment.' },
  { hobby: 'Fitness', category: 'Shakers & Bottles', brand: 'MuscleBlaze', product_name: 'MuscleBlaze Smartshaker 700ml', price: 549, image_url: 'https://m.media-amazon.com/images/I/61LS3R2PMTL._SX679_.jpg', official_url: 'https://www.muscleblaze.com/MuscleBlaze-Smartshaker-700ml/p/MBSHKRSMRT1-RED-1', source_type: 'official_product_page', description: 'BPA-free shaker with pill storage and wire whisk.' },
  { hobby: 'Fitness', category: 'Shakers & Bottles', brand: 'MyProtein', product_name: 'MyProtein The Shaker (600ml)', price: 699, image_url: 'https://m.media-amazon.com/images/I/71+g1LdTdIL._SX679_.jpg', official_url: 'https://www.myprotein.com/sports-nutrition/the-shaker/10530268.html', source_type: 'official_product_page', description: 'Iconic leakproof protein shaker, dishwasher-safe.' },

  // -- FITNESS TRACKERS --
  { hobby: 'Fitness', category: 'Fitness Trackers', brand: 'Garmin', product_name: 'Garmin Forerunner 265S', price: 39999, image_url: 'https://m.media-amazon.com/images/I/61UBCzLaeoL._SX679_.jpg', official_url: 'https://www.garmin.com/en-IN/p/884585', source_type: 'official_product_page', description: 'AMOLED GPS running smartwatch with advanced metrics.' },
  { hobby: 'Fitness', category: 'Fitness Trackers', brand: 'Fitbit', product_name: 'Fitbit Charge 6', price: 14999, image_url: 'https://m.media-amazon.com/images/I/71X2JMiGaQL._SX679_.jpg', official_url: 'https://www.fitbit.com/in/products/trackers/charge6', source_type: 'official_product_page', description: 'Advanced fitness tracker with ECG and GPS.' },
  { hobby: 'Fitness', category: 'Fitness Trackers', brand: 'Amazfit', product_name: 'Amazfit Band 7', price: 3999, image_url: 'https://m.media-amazon.com/images/I/51j60W6FNiL._SX679_.jpg', official_url: 'https://www.amazfit.com/en/band7', source_type: 'official_product_page', description: 'Budget fitness band with 18-day battery and SpO2.' },
  { hobby: 'Fitness', category: 'Fitness Trackers', brand: 'Noise', product_name: 'Noise ColorFit Pro 5', price: 2999, image_url: 'https://m.media-amazon.com/images/I/71LMfQJkjvL._SX679_.jpg', official_url: 'https://www.gonoise.com/products/noise-colorfit-pro-5', source_type: 'official_product_page', description: 'AMOLED budget smartwatch with 100+ sports modes.' },

  // -- SUPPLEMENTS --
  { hobby: 'Fitness', category: 'Supplements', brand: 'Optimum Nutrition', product_name: 'ON Gold Standard Whey 5lb', price: 8299, image_url: 'https://m.media-amazon.com/images/I/81MUFxrPEFL._SX679_.jpg', official_url: 'https://www.amazon.in/Optimum-Nutrition-Standard-Protein-Flavour/dp/B00BEO9PH4', source_type: 'distributor', description: '100% whey protein, 24g protein per serving, 77 servings.' },
  { hobby: 'Fitness', category: 'Supplements', brand: 'MuscleBlaze', product_name: 'MuscleBlaze Biozyme Performance Whey 2kg', price: 3149, image_url: 'https://m.media-amazon.com/images/I/71b0WtAZ3PL._SX679_.jpg', official_url: 'https://www.muscleblaze.com/MuscleBlaze-Biozyme-Performance-Whey-2-kg/p/MBWBZP-RCHCLT-2KG', source_type: 'official_product_page', description: 'Whey with Digezyme, 27g protein per serving.' },
  { hobby: 'Fitness', category: 'Supplements', brand: 'Wellcore', product_name: 'Wellcore Daily Whey 1kg', price: 1999, image_url: 'https://m.media-amazon.com/images/I/71L7ppbj4fL._SX679_.jpg', official_url: 'https://www.wellcore.in/products/daily-whey', source_type: 'official_product_page', description: 'Pure whey protein concentrate, 25g protein per serving.' },
  { hobby: 'Fitness', category: 'Supplements', brand: 'Nutrabay', product_name: 'Nutrabay Gold 100% Whey Isolate 2kg', price: 3599, image_url: 'https://m.media-amazon.com/images/I/71dvfAVHmNL._SX679_.jpg', official_url: 'https://nutrabay.com/products/nutrabay-gold-100-whey-protein-isolate', source_type: 'official_product_page', description: 'Pure whey isolate, 28g protein, zero sugar.' },

  // ================================================================
  // TRAVEL
  // ================================================================

  // -- BACKPACKS --
  { hobby: 'Travel', category: 'Backpacks', brand: 'Wildcraft', product_name: 'Wildcraft Trailblazer 45L Rucksack', price: 2499, image_url: 'https://m.media-amazon.com/images/I/71ZpT7EwJHL._SX679_.jpg', official_url: 'https://wildcraft.com/rucksacks', source_type: 'official_brand_page', description: 'Durable trekking rucksack with rain cover and hip belt.' },
  { hobby: 'Travel', category: 'Backpacks', brand: 'Decathlon', product_name: 'Decathlon Quechua 30L Hiking Backpack', price: 1999, image_url: 'https://contents.mediadecathlon.com/p2294524/k$2a7c19d8f47b7a87e3b6c527432caef4/nh-escape-500-30-litre-country-walking-backpack.jpg', official_url: 'https://www.decathlon.in/p/8546866/30-l-country-walking-backpack-nh-escape-500', source_type: 'official_product_page', description: '30L country walking backpack with ventilated back.' },
  { hobby: 'Travel', category: 'Backpacks', brand: 'American Tourister', product_name: 'American Tourister Ebony 25L Backpack', price: 2195, image_url: 'https://m.media-amazon.com/images/I/71HJL4BXQRL._SX679_.jpg', official_url: 'https://www.americantourister.com/collections/backpacks', source_type: 'official_brand_page', description: 'Laptop backpack with 15.6" compartment.' },
  { hobby: 'Travel', category: 'Backpacks', brand: 'Skybags', product_name: 'Skybags Trek 36L Rucksack', price: 1699, image_url: 'https://m.media-amazon.com/images/I/71JzBdqxAYL._SX679_.jpg', official_url: 'https://www.skybags.co.in/bags/rucksacks', source_type: 'official_brand_page', description: 'Polyester trekking backpack with multiple pockets.' },

  // -- TROLLEY BAGS --
  { hobby: 'Travel', category: 'Trolley Bags', brand: 'American Tourister', product_name: 'American Tourister Trigard Spinner 77cm', price: 5595, image_url: 'https://m.media-amazon.com/images/I/71M8M+jPYeL._SX679_.jpg', official_url: 'https://www.americantourister.com/collections/hard-side-luggage', source_type: 'official_brand_page', description: '77cm large spinner hardside luggage with TSA lock.' },
  { hobby: 'Travel', category: 'Trolley Bags', brand: 'Samsonite', product_name: 'Samsonite Octolite Spinner 69cm', price: 9995, image_url: 'https://m.media-amazon.com/images/I/71Dl-DaQfXL._SX679_.jpg', official_url: 'https://www.samsonite.in/luggage/spinner-69cm', source_type: 'official_brand_page', description: 'Lightweight 69cm spinner trolley, 2.4kg weight.' },
  { hobby: 'Travel', category: 'Trolley Bags', brand: 'Safari', product_name: 'Safari Thorium 8W 65cm Trolley', price: 4999, image_url: 'https://m.media-amazon.com/images/I/71zNxF6MH2L._SX679_.jpg', official_url: 'https://safaribags.com/collections/trolley-bags', source_type: 'official_brand_page', description: '65cm medium hardshell trolley with 8 wheels.' },
  { hobby: 'Travel', category: 'Trolley Bags', brand: 'VIP', product_name: 'VIP Centaurus Spinner 69cm', price: 5499, image_url: 'https://m.media-amazon.com/images/I/71k9aUzV3aL._SX679_.jpg', official_url: 'https://vipindustries.com/collections/hard-luggage', source_type: 'official_brand_page', description: '69cm medium polypropylene trolley bag.' },

  // -- TRAVEL ACCESSORIES --
  { hobby: 'Travel', category: 'Travel Accessories', brand: 'UGREEN', product_name: 'UGREEN Travel Cable Organizer Bag', price: 999, image_url: 'https://m.media-amazon.com/images/I/71LYuqH8ZEL._SX679_.jpg', official_url: 'https://www.ugreen.com/products/ugreen-cable-organizer-bag', source_type: 'official_product_page', description: 'Compact travel organizer for cables, adapters, and earphones.' },
  { hobby: 'Travel', category: 'Travel Accessories', brand: 'Portronics', product_name: 'Portronics Adapto 65W Universal Travel Adapter', price: 1499, image_url: 'https://m.media-amazon.com/images/I/61EUMrDDfcL._SX679_.jpg', official_url: 'https://www.portronics.com/products/adapto-65', source_type: 'official_product_page', description: 'Universal travel adapter with 65W USB-C PD for 150+ countries.' },
  { hobby: 'Travel', category: 'Travel Accessories', brand: 'Amazon Basics', product_name: 'Amazon Basics Packing Cubes (6-Set)', price: 799, image_url: 'https://m.media-amazon.com/images/I/81D8ej8jKBL._SX679_.jpg', official_url: 'https://www.amazon.in/AmazonBasics-Packing-Travel-Organizer-Cubes/dp/B014VBGYL8', source_type: 'distributor', description: '6-piece lightweight luggage packing organizer set.' },
  { hobby: 'Travel', category: 'Travel Accessories', brand: 'Decathlon', product_name: 'Decathlon Forclaz 1L Hip Flask Water Bottle', price: 499, image_url: 'https://contents.mediadecathlon.com/p2227780/k$a7e94b72c4e4c9b56e4e57f5c9dc7484/trek-1-litre-soft-water-flask.jpg', official_url: 'https://www.decathlon.in/p/8549162/trek-1-litre-soft-flask', source_type: 'official_product_page', description: '1L collapsible soft flask for trekking and travel.' },

  // -- TRAVEL FOOTWEAR --
  { hobby: 'Travel', category: 'Travel Footwear', brand: 'Decathlon', product_name: 'Decathlon NH100 Hiking Shoes', price: 1499, image_url: 'https://contents.mediadecathlon.com/p2243148/k$35e2e7e7e82b5fd5c95b2b1e52e2e7e7/nh100-mid-men-s-waterproof-country-hiking-boots.jpg', official_url: 'https://www.decathlon.in/p/8549169/nh100-mid-men-s-waterproof-country-hiking-boots', source_type: 'official_product_page', description: 'Waterproof mid-cut hiking boots for trail walking.' },
  { hobby: 'Travel', category: 'Travel Footwear', brand: 'Woodland', product_name: 'Woodland GC 2651117 Trekking Shoes', price: 4999, image_url: 'https://m.media-amazon.com/images/I/71tXoW4VkAL._SX679_.jpg', official_url: 'https://www.woodlandworldwide.com/shoes/trekking', source_type: 'official_brand_page', description: 'Genuine leather hiking shoes with anti-skid sole.' },
  { hobby: 'Travel', category: 'Travel Footwear', brand: 'Adidas', product_name: 'Adidas Terrex AX4 Hiking Shoes', price: 8999, image_url: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ca8c5a19b9254edcaa95af1000e65083_9366/Terrex_AX4_Hiking_Shoes_Blue_HP7391_01_standard.jpg', official_url: 'https://www.adidas.co.in/terrex-ax4-hiking-shoes/HP7391.html', source_type: 'official_product_page', description: 'Lightweight hiking shoes with TRAXION outsole.' },
  { hobby: 'Travel', category: 'Travel Footwear', brand: 'Skechers', product_name: 'Skechers Stamina 2 Nuevo Walk Shoe', price: 3999, image_url: 'https://m.media-amazon.com/images/I/71gJ08HTPTL._SX679_.jpg', official_url: 'https://www.skechers.com.in/men/sport-performance/walking', source_type: 'official_brand_page', description: 'Memory foam walking shoes, lightweight and breathable.' }
];

async function seed() {
  console.log('Fetching hobbies...');
  const { data: hobbies } = await supabase.from('hobbies').select('id, hobby_name');
  const hobbyMap = {};
  hobbies.forEach(h => { hobbyMap[h.hobby_name] = h.id; });

  const mapped = CATALOG.map(p => ({
    hobby_id: hobbyMap[p.hobby],
    category: p.category,
    brand: p.brand,
    product_name: p.product_name,
    price: p.price,
    image_url: p.image_url,
    official_url: p.official_url,
    source_type: p.source_type,
    description: p.description
  })).filter(p => p.hobby_id);

  console.log(`Inserting ${mapped.length} unique products...`);
  const { error } = await supabase.from('products').insert(mapped);
  if (error) console.error('Error:', error);
  else console.log('✓ Seeding complete! All products inserted.');
}

seed();
